import 'package:dio/dio.dart';
import 'package:menu_pal_server/src/generated/protocol.dart';
import 'package:serverpod/serverpod.dart';

// This is an example endpoint of your server. It's best practice to use the
// `Endpoint` ending of the class name, but it will be removed when accessing
// the endpoint from the client. I.e., this endpoint can be accessed through
// `client.example` on the client side.

// After adding or modifying an endpoint, you will need to run
// `serverpod generate` to update the server and client code.
class WorkPlaceEndpoint extends Endpoint {
  // You create methods in your endpoint which are accessible from the client by
  // creating a public method with `Session` as its first parameter.
  // `bool`, `int`, `double`, `String`, `UuidValue`, `Duration`, `DateTime`, `ByteData`,
  // and other serializable classes, exceptions and enums from your from your `protocol` directory.
  // The methods should return a typed future; the same types as for the parameters are
  // supported. The `session` object provides access to the database, logging,
  // passwords, and information about the request being made to the server.
  Future<void> workHere(Session session, String name) async {
    print("workHere worked");

    //
    //
    //////////////////////-------SET DATAS TO DB---------////////////////////

    //1---)  // await RestaurantType.db.insert(session, restaurantTypes);
    //2---)
    /*  await Country.db.insertRow(
        session,
        Country(
            name: "Türkiye",
            population: 90000000,
            createdBy: "Onur",
            timezone: "GMT+3")); */
    //3---)  await City.db.insert(session, cities);

    //4---) await getDistrictByCity(session);
    //5---) await getTownByDistrict(session);

    //////////////////////----------------////////////////////
  }

  Future<void> getDistrictByCity(Session sessioncities) async {
    List<City> cities = await City.db.find(sessioncities);

    List<District> districts = [];
    var offset = 0;
    for (var i = 0; i < 10000; i++) {
      offset = i * 700;
      var url =
          'https://turkiyeapi.dev/api/v1/districts?offset=$offset&limit=700';
      print(url);

      Response response;

      try {
        response = await Dio().get(url);
        print(response.data["status"]);
      } catch (e) {
        print(e.toString());
        break;
      }

      for (var e in response.data["data"]) {
        districts.add(District(
          cityId:
              cities.firstWhere((element) => element.name == e["province"]).id,
          name: e["name"],
          createdAt: DateTime.now().toUtc(),
          latitude: e["latitude"],
          longitude: e["longitude"],
          population: e["population"],
          area: e["area"],
          timezone: e["timezone"],
        ));
      }
    }

    await District.db.insert(sessioncities, districts);
  }

  Future<void> getTownByDistrict(Session session) async {
    List<District> districts = await District.db.find(session);
    List<Town> towns = [];
    var offset = 0;
    for (var i = 0; i < 10000; i++) {
      offset = i * 700;
      var url =
          'https://turkiyeapi.dev/api/v1/neighborhoods?offset=$offset&limit=700';
      print(url);

      Response response;

      try {
        response = await Dio().get(url);
        print(response.data["status"]);
      } catch (e) {
        print(e.toString());
        break;
      }

      for (var e in response.data["data"]) {
        towns.add(Town(
          districtId: districts
              .firstWhere((element) => element.name == e["district"])
              .id,
          name: e["name"],
          createdAt: DateTime.now().toUtc(),
          population: e["population"],
        ));
      }
    }

    await Town.db.insert(session, towns);
  }
}

List<City> cities = [
  City(
    name: 'Adana',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.0017,
    longitude: 35.3285,
    population: 2261272,
    area: 14030,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Adıyaman',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.7645,
    longitude: 38.2782,
    population: 630322,
    area: 7474,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Afyonkarahisar',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.7633,
    longitude: 30.5408,
    population: 746236,
    area: 14545,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Ağrı',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.7021,
    longitude: 43.0505,
    population: 535215,
    area: 11658,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Aksaray',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.3924,
    longitude: 34.0297,
    population: 417197,
    area: 7697,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Amasya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.6535,
    longitude: 35.8318,
    population: 326116,
    area: 5665,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Ankara',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.9334,
    longitude: 32.8597,
    population: 5503985,
    area: 25132,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Antalya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 36.8969,
    longitude: 30.7133,
    population: 2471665,
    area: 20516,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Ardahan',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.1100,
    longitude: 42.7024,
    population: 99233,
    area: 5576,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Artvin',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.1824,
    longitude: 41.8182,
    population: 166858,
    area: 3143,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Aydın',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.8489,
    longitude: 27.4005,
    population: 1126855,
    area: 8298,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Balıkesir',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.6489,
    longitude: 27.8822,
    population: 1200382,
    area: 14096,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bartın',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.5811,
    longitude: 32.4610,
    population: 198249,
    area: 2140,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Batman',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.8833,
    longitude: 41.1322,
    population: 620278,
    area: 4649,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bayburt',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.2588,
    longitude: 40.2286,
    population: 82074,
    area: 3739,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bilecik',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.1744,
    longitude: 29.9765,
    population: 222776,
    area: 4231,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bingöl',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.0635,
    longitude: 40.8250,
    population: 291537,
    area: 8498,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bitlis',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.3965,
    longitude: 42.1217,
    population: 303255,
    area: 8367,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bolu',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.5669,
    longitude: 31.1561,
    population: 313320,
    area: 8005,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Burdur',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.7216,
    longitude: 30.2877,
    population: 272635,
    area: 6968,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Bursa',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.1826,
    longitude: 29.0665,
    population: 3038216,
    area: 10693,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Çanakkale',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.1533,
    longitude: 26.4090,
    population: 549556,
    area: 10066,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Çankırı',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.6013,
    longitude: 33.6135,
    population: 197411,
    area: 7302,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Çorum',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.5506,
    longitude: 34.9556,
    population: 536483,
    area: 12643,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Denizli',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.7767,
    longitude: 29.0878,
    population: 1030670,
    area: 12441,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Diyarbakır',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.9092,
    longitude: 40.2392,
    population: 1810427,
    area: 15148,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Düzce',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.8438,
    longitude: 31.1565,
    population: 392166,
    area: 2594,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Edirne',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.6764,
    longitude: 26.5551,
    population: 166452,
    area: 6031,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Elazığ',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.6813,
    longitude: 39.2269,
    population: 384100,
    area: 9488,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Erzincan',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.7524,
    longitude: 39.6100,
    population: 231538,
    area: 11056,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Erzurum',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.9334,
    longitude: 41.2764,
    population: 761803,
    area: 25415,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Eskişehir',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.7768,
    longitude: 30.5206,
    population: 883170,
    area: 4255,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Gaziantep',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.0662,
    longitude: 37.3833,
    population: 2005110,
    area: 7255,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Giresun',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.9132,
    longitude: 38.3927,
    population: 450920,
    area: 6113,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Gümüşhane',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.4650,
    longitude: 39.4570,
    population: 149975,
    area: 6092,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Hakkari',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.5788,
    longitude: 43.7343,
    population: 116783,
    area: 7870,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Hatay',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 36.2878,
    longitude: 36.3281,
    population: 1681638,
    area: 21459,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Iğdır',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.9080,
    longitude: 44.0077,
    population: 195232,
    area: 3570,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Isparta',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.7661,
    longitude: 30.5552,
    population: 442964,
    area: 9756,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'İstanbul',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.0082,
    longitude: 28.9784,
    population: 15529280,
    area: 5343,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'İzmir',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.4192,
    longitude: 27.1287,
    population: 4367256,
    area: 12144,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kahramanmaraş',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.5736,
    longitude: 36.9375,
    population: 1124344,
    area: 14433,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Karabük',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.2044,
    longitude: 32.6236,
    population: 243614,
    area: 4145,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Karaman',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.1759,
    longitude: 33.2287,
    population: 254919,
    area: 8854,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kars',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.6013,
    longitude: 43.0970,
    population: 284923,
    area: 9857,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kastamonu',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.3887,
    longitude: 33.7827,
    population: 379405,
    area: 13272,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kayseri',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.7225,
    longitude: 35.4875,
    population: 1412934,
    area: 17043,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kırıkkale',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.8467,
    longitude: 33.5153,
    population: 278703,
    area: 4565,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kırklareli',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.7333,
    longitude: 27.2167,
    population: 361836,
    area: 6550,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kırşehir',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.1428,
    longitude: 34.1709,
    population: 241868,
    area: 6562,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kilis',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 36.7184,
    longitude: 37.1212,
    population: 145826,
    area: 1428,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kocaeli',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.8533,
    longitude: 29.8815,
    population: 2042561,
    area: 3414,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Konya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.8746,
    longitude: 32.4932,
    population: 2302577,
    area: 40681,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Kütahya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.4242,
    longitude: 29.9837,
    population: 571363,
    area: 11875,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Malatya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.3554,
    longitude: 38.3095,
    population: 812580,
    area: 12213,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Manisa',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.6121,
    longitude: 27.4265,
    population: 1452799,
    area: 13269,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Mardin',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.3212,
    longitude: 40.7245,
    population: 868757,
    area: 8882,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Mersin',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 36.8121,
    longitude: 34.6415,
    population: 1851498,
    area: 15853,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Muğla',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.2153,
    longitude: 28.3636,
    population: 1057161,
    area: 12654,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Muş',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.9462,
    longitude: 41.7539,
    population: 409536,
    area: 8196,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Nevşehir',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.6939,
    longitude: 34.6857,
    population: 305896,
    area: 5667,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Niğde',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.9763,
    longitude: 34.6939,
    population: 362071,
    area: 7312,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Ordu',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.9839,
    longitude: 37.8764,
    population: 771932,
    area: 6001,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Osmaniye',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.0743,
    longitude: 36.2471,
    population: 559405,
    area: 3357,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Rize',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.0201,
    longitude: 40.5235,
    population: 344359,
    area: 3920,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Sakarya',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.7565,
    longitude: 30.3782,
    population: 1088165,
    area: 4821,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Samsun',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.2867,
    longitude: 36.33,
    population: 1370356,
    area: 9601,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Siirt',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.9273,
    longitude: 41.9419,
    population: 331070,
    area: 5450,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Sinop',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 42.0267,
    longitude: 35.1625,
    population: 218243,
    area: 5862,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Sivas',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.7477,
    longitude: 37.0179,
    population: 646608,
    area: 28488,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Şanlıurfa',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.1676,
    longitude: 38.7955,
    population: 2176145,
    area: 19091,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Şırnak',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 37.4187,
    longitude: 42.4918,
    population: 537762,
    area: 7152,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Tekirdağ',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.9780,
    longitude: 27.5111,
    population: 1116375,
    area: 6223,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Tokat',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.3167,
    longitude: 36.5544,
    population: 602662,
    area: 10071,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Trabzon',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.0015,
    longitude: 39.7178,
    population: 808974,
    area: 4685,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Tunceli',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.3074,
    longitude: 39.4388,
    population: 83596,
    area: 7774,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Uşak',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.6809,
    longitude: 29.4082,
    population: 370509,
    area: 5537,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Van',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 38.5012,
    longitude: 43.3836,
    population: 1100190,
    area: 19469,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Yalova',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 40.6556,
    longitude: 29.2769,
    population: 291001,
    area: 847,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Yozgat',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 39.8181,
    longitude: 34.8144,
    population: 418500,
    area: 14123,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
  City(
    name: 'Zonguldak',
    countryId: 1,
    createdAt: DateTime.now().toUtc(),
    latitude: 41.4564,
    longitude: 31.7987,
    population: 599698,
    area: 3304,
    currency: 'TRY',
    timezone: 'GMT+3',
  ),
];

List<RestaurantType> restaurantTypes = [
  RestaurantType(
    name: 'Bar',
    description: 'Beer, cocktail',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Cafe',
    description: 'Coffee, pastries',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Fine Dining',
    description: 'Gourmet meals, formal atmosphere',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Fast Food',
    description: 'Burgers, fries, quick service',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Casual Dining',
    description: 'Comfort food, relaxed atmosphere',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Buffet',
    description: 'All-you-can-eat, various cuisines',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Food Truck',
    description: 'Street food, fast service',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Bistro',
    description: 'Small, casual, simple meals',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Steakhouse',
    description: 'Steak, meat dishes',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Pizzeria',
    description: 'Pizza, Italian food',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Seafood',
    description: 'Fish, shellfish, seafood specialties',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Dessert Shop',
    description: 'Cakes, ice cream, sweets',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Vegetarian',
    description: 'Plant-based dishes',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Vegan',
    description: 'Dairy-free, meat-free meals',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Sushi Bar',
    description: 'Sushi, Japanese cuisine',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Grill',
    description: 'Barbecue, grilled dishes',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Diner',
    description: 'American comfort food, breakfast all day',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Bakery',
    description: 'Breads, pastries, baked goods',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Pub',
    description: 'Beer, casual drinks, pub food',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Tapas Bar',
    description: 'Spanish small plates, wine',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Gastropub',
    description: 'Gourmet food, craft beers',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Ice Cream Parlor',
    description: 'Ice cream, frozen desserts',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Juice Bar',
    description: 'Fresh juices, smoothies',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Teahouse',
    description: 'Tea, light snacks',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Brasserie',
    description: 'French-style, casual dining',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'BBQ Joint',
    description: 'Smoked meats, barbecue',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Ramen Shop',
    description: 'Ramen, Japanese noodles',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Kebab Shop',
    description: 'Grilled meats, kebabs',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Dim Sum House',
    description: 'Chinese small dishes, tea',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Creperie',
    description: 'Crepes, light French meals',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Fondue Restaurant',
    description: 'Fondue, melted cheese and chocolate',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Taco Stand',
    description: 'Tacos, Mexican street food',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Steamboat Restaurant',
    description: 'Hot pot, Asian soups',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Curry House',
    description: 'Indian curries, spices',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Fried Chicken Shop',
    description: 'Fried chicken, quick service',
    createdAt: DateTime.now().toUtc(),
  ),
  RestaurantType(
    name: 'Shawarma Stand',
    description: 'Shawarma, Middle Eastern street food',
    createdAt: DateTime.now().toUtc(),
  ),
];
