// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmm-mqYvY44KC1LKn5U8OZQ6-wRG4SzGg',
    appId: '1:876454931653:web:8b003d7b83903f1f94d4ac',
    messagingSenderId: '876454931653',
    projectId: 'menupal-dee10',
    authDomain: 'menupal-dee10.firebaseapp.com',
    storageBucket: 'menupal-dee10.appspot.com',
    measurementId: 'G-YXSMDDNL6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DLEvRDIcStQ3_v-lPcQH8hDfw7TlUXc',
    appId: '1:876454931653:android:073f019fc1db8d0594d4ac',
    messagingSenderId: '876454931653',
    projectId: 'menupal-dee10',
    storageBucket: 'menupal-dee10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-4gV3JOUKobz_WgXz3ghktVYNUPwcAQ',
    appId: '1:876454931653:ios:20a3f4bf9a71b6f994d4ac',
    messagingSenderId: '876454931653',
    projectId: 'menupal-dee10',
    storageBucket: 'menupal-dee10.appspot.com',
    iosBundleId: 'dev.onurbulut.menuPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-4gV3JOUKobz_WgXz3ghktVYNUPwcAQ',
    appId: '1:876454931653:ios:20a3f4bf9a71b6f994d4ac',
    messagingSenderId: '876454931653',
    projectId: 'menupal-dee10',
    storageBucket: 'menupal-dee10.appspot.com',
    iosBundleId: 'dev.onurbulut.menuPal',
  );

}