# This is the configuration file for your production environment.
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the menupalpod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  # publicHost: api.menupalpod.com
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  # publicHost: insights.menupalpod.com
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  # publicHost: app.menupalpod.com
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers. The default for the Google Cloud
# Engine Terraform configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. database.menupalpod.com.
database:
  # host: database.private-production.menupalpod.com
  port: 5432
  name: serverpod
  user: postgres
  requireSsl: true

# This is the setup for Redis. The default for the Google Cloud Engine Terraform
# configuration is to connect on a private IP address.
# If you are connecting on a public IP (e.g. on AWS or Google Cloud Run), you
# connect on the public IP of the database e.g. redis.menupalpod.com.
redis:
  enabled: false
  # host: redis.private-production.menupalpod.com
  port: 6379
